DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='music_app') THEN
    CREATE ROLE music_app LOGIN PASSWORD 'music_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='music_worker') THEN
    CREATE ROLE music_worker LOGIN PASSWORD 'music_worker' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT BYPASSRLS;
  END IF;
END $$;
GRANT CONNECT ON DATABASE music TO music_app, music_worker;
