#!/usr/bin/env python3
"""Resident drill for the second factor (release gate G10-MFA) against the running stack.

What this is not: a test of the TOTP arithmetic. That lives in
tests/unit/test_mfa_second_factor.py, where it is checked against an independent RFC 6238
implementation and the eighteen published Appendix B vectors. What needs a stack is everything that
only exists at a boundary: the shape of the pending credential, which session a code is allowed to
unlock, and what the database is left holding after each transition. Codes here are generated by
e2e_client.totp_code(), which is deliberately not the library the server verifies with.

Fixtures are provisioned by SQL for the same reason the erasure drill does it: this deployment has
no registration endpoint. Neither probe joins a workspace, because every endpoint here is
authenticated rather than workspace-scoped, and one less row means one less thing to tear down.
Each run still leaves audit events behind -- append-only by schema design
(001_production_candidate.sql:468) -- so the residue is printed rather than scrubbed.

Login is counted per account and throttled at ten a minute with a sliding window, so this drill
mints one pending token and reuses it: a pending token buys nothing on its own, because every
challenge still has to clear the single-use step/recovery guard.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import time
import uuid

import httpx

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
import e2e_client  # noqa: E402

BASE = os.getenv("API_BASE_URL", "http://localhost:8000") + "/api"
STAMP = time.strftime("%H%M%S", time.gmtime()) + uuid.uuid4().hex[:6]
PROBE = f"mfa-probe-{STAMP}@example.local"
WINDOW_PROBE = f"mfa-window-probe-{STAMP}@example.local"
PASSWORD = "demo-owner"
OTHER_SEED = "JBSWY3DPEHPK3PXP"  # a valid-shaped seed that is not the probe's
checks: list[tuple[str, bool, str]] = []


def sql(statement: str) -> str:
    out = subprocess.run(["docker", "compose", "exec", "-T", "postgres", "psql", "-U", "music_admin", "-d", "music",
                          "-tAc", " ".join(statement.split())], capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"psql failed: {out.stderr.strip()[:300]}")
    return out.stdout.strip().splitlines()[0].strip() if out.stdout.strip() else ""


def check(name: str, passed: bool, detail: str = ""):
    checks.append((name, bool(passed), detail))
    print(f"  {'OK  ' if passed else 'FAIL'} {name}" + ("" if passed else f" — {detail}"))


def make_user(email: str, display: str) -> str:
    return sql(f"""INSERT INTO users(email,display_name,password_hash,is_platform_admin)
      SELECT '{email}','{display}',password_hash,false FROM users WHERE email='owner@example.local'
      RETURNING id""")


def bearer(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


def sign_in(email: str) -> httpx.Response:
    """One raw login. e2e_client.login refuses a second factor on purpose, so this drill reads
    the response shape itself."""
    return httpx.post(BASE + "/auth/login", json={"email": email, "password": PASSWORD}, timeout=40)


def pending_token(email: str) -> str:
    response = sign_in(email)
    body = response.json() if response.status_code == 200 else {}
    if not body.get("mfa_required"):
        raise SystemExit(f"expected a second-factor challenge for {email}, got {response.status_code} {response.text[:200]}")
    return body["pending_token"]


def challenge(token: str, code: str) -> httpx.Response:
    return httpx.post(BASE + "/auth/mfa/challenge", json={"pending_token": token, "code": code}, timeout=40)


def redis_cli(*arguments: str) -> str:
    out = subprocess.run(["docker", "compose", "exec", "-T", "redis", "redis-cli", *arguments],
                         capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"redis-cli failed: {out.stderr.strip()[:200]}")
    return out.stdout.strip()


def wait_out_challenge_window(user_id: str):
    """The challenge limiter is a 60s fixed window, so read it rather than sleeping blind.

    Sleeping a flat 61s would work too, but it would also hide a limiter whose TTL had been set
    wrong: this asks the store how much of the window is left, waits that much, and then requires
    the counter to be actually gone before the next measurement is taken.
    """
    key = f"mfa:challenge:{hashlib.sha256(user_id.encode()).hexdigest()}"
    for _ in range(10):
        ttl = int(redis_cli("TTL", key) or -2)
        if ttl < 0:
            return
        time.sleep(ttl + 1)


def status(token: str) -> dict:
    response = httpx.get(BASE + "/auth/mfa/status", headers=bearer(token), timeout=40)
    if response.status_code != 200:
        return {"_status": response.status_code, "_body": response.text[:200]}
    return response.json()


def stored_recovery_hashes(user_id: str) -> list[str]:
    raw = sql(f"SELECT mfa_recovery FROM users WHERE id='{user_id}'")
    return [entry["hash"] for entry in json.loads(raw)] if raw and raw != "-" else []


def main() -> int:
    probe_id = make_user(PROBE, "MFA Probe")
    window_id = make_user(WINDOW_PROBE, "MFA Window Probe")
    sessions_at = lambda: sql(f"SELECT count(*) FROM auth_sessions WHERE user_id='{probe_id}'")
    try:
        # ---- two password-only sessions exist before anything is armed ---------------
        first = sign_in(PROBE)
        check("an unarmed account still logs in with a password alone",
              first.status_code == 200 and "access_token" in first.json(), f"{first.status_code} {first.text[:200]}")
        s1 = first.json()["access_token"]
        second = sign_in(PROBE)
        s2 = second.json()["access_token"]
        check("a second session can be open at the same time", second.status_code == 200, f"{second.status_code}")
        check("that second session works before arming",
              httpx.get(BASE + "/auth/me", headers=bearer(s2), timeout=40).status_code == 200)
        check("and each login minted its own session row", sessions_at() == "2", sessions_at())

        # ---- enrolment is staged: a seed alone must not arm anything -----------------
        enrolled = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(s1), timeout=40)
        seed = enrolled.json().get("secret", "") if enrolled.status_code == 200 else ""
        uri = enrolled.json().get("provisioning_uri", "") if enrolled.status_code == 200 else ""
        check("enrolment returns a seed and an otpauth URI", bool(seed) and uri.startswith("otpauth://"),
              f"{enrolled.status_code} {enrolled.text[:200]}")
        check("the URI states the period and digits the server will verify with",
              "period=30" in uri and "digits=6" in uri, uri)
        state = status(s1)
        check("the seed is pending rather than armed", state.get("armed") is False and state.get("pending_since"), str(state))

        wrong = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": "000000"}, headers=bearer(s1), timeout=40)
        check("a wrong code does not arm the factor", wrong.status_code == 401, f"{wrong.status_code} {wrong.text[:160]}")
        check("and the account is still unarmed after it", status(s1).get("armed") is False)
        foreign = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(OTHER_SEED)},
                             headers=bearer(s1), timeout=40)
        check("a well-formed code for some other seed is refused too", foreign.status_code == 401,
              f"{foreign.status_code} {foreign.text[:160]}")

        # Starting over while a seed is still pending is allowed -- nothing is armed yet, so there
        # is no lockout to protect against -- but it has to actually replace the seed, or the
        # abandoned URI keeps working in parallel with the new one.
        replaced = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(s1), timeout=40)
        check("re-enrolment while pending is allowed and hands out a different seed",
              replaced.status_code == 200 and replaced.json().get("secret") not in ("", seed),
              f"{replaced.status_code} {replaced.text[:160]}")
        stale_seed = seed
        seed = replaced.json().get("secret", seed)
        check("and the abandoned seed stops being able to confirm",
              httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(stale_seed)},
                         headers=bearer(s1), timeout=40).status_code == 401)

        armed = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(seed)},
                           headers=bearer(s1), timeout=40)
        body = armed.json() if armed.status_code == 200 else {}
        recovery = body.get("recovery_codes") or []
        check("proof of knowledge arms it, and the recovery codes are shown once",
              armed.status_code == 200 and body.get("armed") is True and len(recovery) == 10,
              f"{armed.status_code} {armed.text[:200]}")
        stored = stored_recovery_hashes(probe_id)
        check("the database kept one hash per code and no plaintext",
              len(stored) == 10 and all(code not in str(stored) and len(code) == 10 for code in recovery),
              f"{len(stored)} hashes")
        old_hashes = set(stored)

        # ---- arming must not retro-authorise, and must not lock out ------------------
        after = status(s1)
        check("the session that proved the code keeps working and records the factor",
              after.get("armed") is True and after.get("session_amr") == "pwd,totp" and after.get("session_second_factor_at"),
              str(after))
        stale = httpx.get(BASE + "/auth/me", headers=bearer(s2), timeout=40)
        check("a session opened before arming is refused until it presents the factor",
              stale.status_code == 401 and "second factor" in stale.text, f"{stale.status_code} {stale.text[:160]}")

        # ---- the password alone now yields a pending credential, not a session -------
        response = sign_in(PROBE)
        challenged = response.json() if response.status_code == 200 else {}
        check("login now stops at a second factor",
              response.status_code == 200 and challenged.get("mfa_required") is True,
              f"{response.status_code} {response.text[:200]}")
        check("its body is nothing but the challenge",
              set(challenged) == {"mfa_required", "pending_token", "pending_expires_in"}, str(sorted(challenged)))
        check("no cookie is set for an unproven login",
              not [c for c in response.headers.get_list("set-cookie") if "resonance_access" in c],
              str(response.headers.get_list("set-cookie")))
        pending = challenged["pending_token"]
        smuggled = httpx.get(BASE + "/auth/me", headers=bearer(pending), timeout=40)
        check("a pending token is refused where an access token is expected",
              smuggled.status_code == 401 and "not an access token" in smuggled.text,
              f"{smuggled.status_code} {smuggled.text[:160]}")
        sessions_before = sessions_at()
        refused = challenge(pending, "000000")
        check("a wrong code at the challenge is refused", refused.status_code == 401, f"{refused.status_code} {refused.text[:160]}")
        check("and mints no session", sessions_at() == sessions_before, f"{sessions_before} -> {sessions_at()}")

        # The enrolment confirmation above consumed the current step, so start counting from it.
        codes = e2e_client.Codes(seed, used=int(time.time() // 30))
        good = codes.next()
        accepted = challenge(pending, good)
        granted = accepted.json() if accepted.status_code == 200 else {}
        check("the right code opens a session", accepted.status_code == 200 and "access_token" in granted,
              f"{accepted.status_code} {accepted.text[:200]}")
        s3 = granted.get("access_token", "")
        check("the challenge body has the same shape as a password-only login",
              set(granted) == set(first.json()), f"{sorted(granted)} vs {sorted(first.json())}")
        third = status(s3) if s3 else {}
        check("the new session records both factors",
              third.get("session_amr") == "pwd,totp" and third.get("session_second_factor_at"), str(third))

        replayed = challenge(pending, good)
        check("the same code cannot be spent twice on the same pending token",
              replayed.status_code == 401, f"{replayed.status_code} {replayed.text[:160]}")
        fresh = pending_token(PROBE)
        across = challenge(fresh, good)
        check("and not on a different pending token either, because the guard is per account",
              across.status_code == 401, f"{across.status_code} {across.text[:160]}")
        check("the replay guard is a stored step rather than process memory",
              sql(f"SELECT coalesce(mfa_last_step::text,'-') FROM users WHERE id='{probe_id}'") != "-")

        # ---- recovery codes: single use, and the count moves -------------------------
        remaining = third.get("recovery_codes_remaining")
        revived = challenge(fresh, recovery[0])
        check("a recovery code opens a session when the phone does not",
              revived.status_code == 200 and "access_token" in revived.json(), f"{revived.status_code} {revived.text[:160]}")
        s4 = revived.json().get("access_token", "")
        used = status(s4) if s4 else {}
        check("using one burns exactly one", used.get("recovery_codes_remaining") == (remaining or 0) - 1,
              f"{remaining} -> {used.get('recovery_codes_remaining')}")
        check("the recovery path is recorded as a distinct method", used.get("session_amr") == "pwd,recovery", str(used))
        check("and the spent code no longer opens anything", challenge(fresh, recovery[0]).status_code == 401)

        # ---- a pending enrolment nobody confirmed has to expire ----------------------
        window_first = sign_in(WINDOW_PROBE)
        window_token = window_first.json()["access_token"]
        began = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(window_token), timeout=40)
        check("a second probe can start its own enrolment", began.status_code == 200, f"{began.status_code} {began.text[:160]}")
        sql(f"UPDATE users SET mfa_secret_issued_at=now()-interval '2 hours' WHERE id='{window_id}'")
        expired = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(began.json()["secret"])},
                             headers=bearer(window_token), timeout=40)
        check("an enrolment left pending past the window cannot be confirmed",
              expired.status_code == 409 and "expired" in expired.text, f"{expired.status_code} {expired.text[:160]}")
        check("and that probe is still unarmed, so an abandoned enrolment locks nobody out",
              sql(f"SELECT (mfa_enrolled_at IS NULL)::text FROM users WHERE id='{window_id}'") == "true")

        # ---- revocation and rotation ------------------------------------------------
        bare = httpx.post(BASE + "/auth/mfa/disable", json={"code": "000000"}, headers=bearer(s1), timeout=40)
        check("dropping the factor asks for the password before anything else",
              bare.status_code == 401 and "password" in bare.text, f"{bare.status_code} {bare.text[:160]}")
        check("and the account stays armed when it is refused", status(s1).get("armed") is True)
        # The code is the half an attacker can still hand over after phishing it; the password is the
        # half a stolen cookie does not carry. Order is the point, and so is what must not happen: a
        # refusal at the password wall must leave the code unspent and still usable.
        proof = codes.next()
        badpw = httpx.post(BASE + "/auth/mfa/disable", json={"code": proof, "password": "not-the-password"},
                           headers=bearer(s1), timeout=40)
        check("a wrong password refuses the drop even while the code is currently valid",
              badpw.status_code == 403 and "password" in badpw.text, f"{badpw.status_code} {badpw.text[:160]}")
        check("the refusal left the second factor armed", status(s1).get("armed") is True)
        again = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(s1), timeout=40)
        check("an armed second factor cannot be replaced behind its own back",
              again.status_code == 409, f"{again.status_code} {again.text[:160]}")

        disabled = httpx.post(BASE + "/auth/mfa/disable", json={"code": proof, "password": PASSWORD},
                              headers=bearer(s1), timeout=40)
        check("the very same code drops the factor once the password is right",
              disabled.status_code == 200 and disabled.json().get("armed") is False, f"{disabled.status_code} {disabled.text[:160]}")
        row = sql(f"SELECT coalesce(mfa_secret_enc,'-')||'|'||coalesce(mfa_recovery::text,'-')||'|'||(mfa_enrolled_at IS NULL)::text"
                  f"||'|'||coalesce(mfa_last_step::text,'-') FROM users WHERE id='{probe_id}'")
        check("seed, recovery set, armed marker and replay step are all gone", row == "-|-|true|-", row)
        plain = sign_in(PROBE)
        check("password-only login works again", plain.status_code == 200 and "access_token" in plain.json()
              and not plain.json().get("mfa_required"), f"{plain.status_code} {plain.text[:160]}")
        check("the disarmed sessions are not retroactively refused",
              httpx.get(BASE + "/auth/me", headers=bearer(s2), timeout=40).status_code == 200)

        # ---- re-enrolment: a fresh seed, and the old recovery set stops working ------
        arm = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(plain.json()["access_token"]), timeout=40)
        new_seed = arm.json().get("secret", "")
        confirmed = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(new_seed)},
                               headers=bearer(plain.json()["access_token"]), timeout=40)
        new_recovery = confirmed.json().get("recovery_codes") or []
        check("re-enrolment arms a fresh seed with a fresh recovery set",
              confirmed.status_code == 200 and confirmed.json().get("armed") is True and len(new_recovery) == 10,
              f"{confirmed.status_code} {confirmed.text[:160]}")
        wait_out_challenge_window(probe_id)
        stale_code = challenge(pending_token(PROBE), recovery[1])
        check("the previous recovery set stops working the moment it is replaced",
              stale_code.status_code == 401, f"{stale_code.status_code} {stale_code.text[:160]}")
        rotated = set(stored_recovery_hashes(probe_id))
        check("and its hashes are gone from the stored set, not merely unused",
              bool(rotated) and not (rotated & old_hashes) and len(rotated) == 10,
              f"{len(rotated)} kept, {len(rotated & old_hashes)} inherited")

        # ---- the code oracle gets a bounded window, and it outranks a valid code -----
        # Everything above shares this account's counter, so the measurements below only mean
        # anything from a quiet window; wait_out_challenge_window(probe_id) cleared one.
        new_codes = e2e_client.Codes(new_seed, used=int(time.time() // 30))
        throttled = pending_token(PROBE)
        statuses = [challenge(throttled, "111111").status_code for _ in range(12)]
        limit = statuses.index(429) + 1 if 429 in statuses else None
        check("repeated wrong codes are throttled", limit is not None, f"statuses: {statuses}")
        check("the throttle does not fire on the first attempt", bool(limit) and limit > 1, f"429 at attempt {limit}")
        check("and the window is monotone: nothing succeeds after it has filled",
              limit is not None and set(statuses[:limit - 1]) == {401} and set(statuses[limit - 1:]) == {429},
              f"statuses: {statuses}")
        key = f"mfa:challenge:{hashlib.sha256(probe_id.encode()).hexdigest()}"
        ttl = int(redis_cli("TTL", key) or -2)
        check("the counter is a bounded window in the shared store, not a permanent lock",
              0 < ttl <= 60, f"key {key} TTL {ttl}")
        if limit:
            outranked = challenge(throttled, new_codes.next())
            check("while throttled, even a correct code is refused", outranked.status_code == 429,
                  f"{outranked.status_code} {outranked.text[:120]}")
            time.sleep(max(ttl, 1) + 2)
            released = httpx.post(BASE + "/auth/mfa/disable", json={"code": new_codes.next(), "password": PASSWORD},
                                  headers=bearer(plain.json()["access_token"]), timeout=40)
            check("when the window passes the account is usable again, not locked out",
                  released.status_code == 200, f"{released.status_code} {released.text[:160]}")
        # Precise, because the window probe deliberately leaves something behind: an abandoned
        # enrolment keeps its sealed seed until the account re-enrols, is disarmed or is erased.
        # It is inert -- 015's confirm refuses it past the window, which is the check above -- but a
        # count on "holds any second-factor material" would report it and hide the real question,
        # which is whether anything can still be *unlocked* by what is stored.
        check("no account left behind can be unlocked by a second factor",
              sql("SELECT count(*) FROM users WHERE mfa_enrolled_at IS NOT NULL OR "
                  "(mfa_secret_enc IS NOT NULL AND mfa_secret_issued_at > now()-interval '900 seconds')") == "0",
              sql("SELECT string_agg(email||'='||coalesce(mfa_enrolled_at::text,'-'),', ') FROM users "
                  "WHERE mfa_secret_enc IS NOT NULL OR mfa_enrolled_at IS NOT NULL"))
    finally:
        for email, user_id in ((PROBE, probe_id), (WINDOW_PROBE, window_id)):
            sql(f"DELETE FROM auth_sessions WHERE user_id='{user_id}'")
            sql(f"DELETE FROM user_preferences WHERE user_id='{user_id}'")
            sql(f"DELETE FROM workspace_members WHERE user_id='{user_id}'")
            sql(f"DELETE FROM users WHERE id='{user_id}'")
        left = sql(f"SELECT count(*) FROM users WHERE id IN ('{probe_id}','{window_id}')")
        sealed = sql("SELECT count(*) FROM users WHERE mfa_secret_enc IS NOT NULL OR mfa_enrolled_at IS NOT NULL")
        events = sql(f"SELECT count(*) FROM audit_events WHERE action LIKE 'auth.mfa.%'")
        print(f"  teardown: probe accounts deleted ({left} still present); accounts on this stack still "
              f"holding second-factor material: {sealed}; auth.mfa.* audit rows retained by design: {events}")

    failed = [name for name, passed, _ in checks if not passed]
    print(f"\nmfa drill: {len(checks) - len(failed)}/{len(checks)} checks passed")
    for name in failed:
        print(f"  - {name}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
