#!/usr/bin/env python3
"""Resident drill for the second factor (release gate G10-MFA) against the running stack.

What this is not: a test of the TOTP arithmetic. That lives in
tests/unit/test_mfa_second_factor.py, where it is checked against an independent RFC 6238
implementation and the eighteen published Appendix B vectors. What needs a stack is everything that
only exists at a boundary: the shape of the pending credential, which session a code is allowed to
unlock, and what the database is left holding after each transition. Codes here are generated by
e2e_client.totp_code(), which is deliberately not the library the server verifies with.

Fixtures are provisioned by SQL for the same reason the erasure drill does it: this deployment has
no registration endpoint. Neither probe joins a workspace, because every endpoint here is
authenticated rather than workspace-scoped, and one less row means one less thing to tear down.
Each run still leaves audit events behind -- append-only by schema design
(001_production_candidate.sql:468) -- so the residue is printed rather than scrubbed.

Login is counted per account at ten failed credentials a minute in a fixed window, and per source at
twenty *different* accounts a minute, so this drill mints one pending token and reuses it: a pending token buys nothing on its own, because every
challenge still has to clear the single-use step/recovery guard. The window's own shape is measured
at the end, against the counter in the shared store.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import time
import uuid
from urllib.parse import quote

import httpx

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
import e2e_client  # noqa: E402

BASE = os.getenv("API_BASE_URL", "http://127.0.0.1:8000") + "/api"
STAMP = time.strftime("%H%M%S", time.gmtime()) + uuid.uuid4().hex[:6]
PROBE = f"mfa-probe-{STAMP}@example.local"
WINDOW_PROBE = f"mfa-window-probe-{STAMP}@example.local"
PASSWORD = "demo-owner"
OTHER_SEED = "JBSWY3DPEHPK3PXP"  # a valid-shaped seed that is not the probe's
checks: list[tuple[str, bool, str]] = []


def sql(statement: str) -> str:
    out = subprocess.run(["docker", "compose", "exec", "-T", "postgres", "psql", "-U", "music_admin", "-d", "music",
                          "-tAc", " ".join(statement.split())], capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"psql failed: {out.stderr.strip()[:300]}")
    return out.stdout.strip().splitlines()[0].strip() if out.stdout.strip() else ""


def check(name: str, passed: bool, detail: str = ""):
    checks.append((name, bool(passed), detail))
    print(f"  {'OK  ' if passed else 'FAIL'} {name}" + ("" if passed else f" — {detail}"))


def make_user(email: str, display: str) -> str:
    return sql(f"""INSERT INTO users(email,display_name,password_hash,is_platform_admin)
      SELECT '{email}','{display}',password_hash,false FROM users WHERE email='owner@example.local'
      RETURNING id""")


def bearer(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


def sign_in(email: str) -> httpx.Response:
    """One raw login. e2e_client.login refuses a second factor on purpose, so this drill reads
    the response shape itself."""
    return httpx.post(BASE + "/auth/login", json={"email": email, "password": PASSWORD}, timeout=40)


def pending_token(email: str) -> str:
    response = sign_in(email)
    body = response.json() if response.status_code == 200 else {}
    if not body.get("mfa_required"):
        raise SystemExit(f"expected a second-factor challenge for {email}, got {response.status_code} {response.text[:200]}")
    return body["pending_token"]


def challenge(token: str, code: str) -> httpx.Response:
    return httpx.post(BASE + "/auth/mfa/challenge", json={"pending_token": token, "code": code}, timeout=40)


def redis_cli(*arguments: str) -> str:
    out = subprocess.run(["docker", "compose", "exec", "-T", "redis", "redis-cli", *arguments],
                         capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"redis-cli failed: {out.stderr.strip()[:200]}")
    return out.stdout.strip()


def api_env(name: str) -> str:
    """Read what the deployed container was actually given, rather than assuming the default."""
    out = subprocess.run(["docker", "compose", "exec", "-T", "api", "printenv", name],
                         capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"printenv {name} failed: {out.stderr.strip()[:200]}")
    return out.stdout.strip()



def container_ip(service: str) -> str:
    """The address a container holds on the compose network right now.

    Read through compose rather than assumed: the api's trust list names the gateway's address, so a
    drift between `networks:` in docker-compose.yml and what the running gateway actually has is the
    failure mode that would silently send every session back to being recorded as the container.
    """
    cid = subprocess.run(["docker", "compose", "ps", "-q", service], capture_output=True, text=True)
    if cid.returncode != 0 or not cid.stdout.strip():
        raise SystemExit(f"compose ps -q {service} gave nothing: {cid.stderr.strip()[:200]}")
    found = subprocess.run(["docker", "inspect", "-f",
                            "{{range .NetworkSettings.Networks}}{{.IPAddress}}\n{{end}}",
                            cid.stdout.strip()], capture_output=True, text=True)
    lines = [x.strip() for x in (found.stdout or "").splitlines() if x.strip()]
    if found.returncode != 0 or not lines:
        raise SystemExit(f"docker inspect for {service} failed: {found.stderr.strip()[:200]}")
    return lines[0]


def container_file(service: str, path: str) -> str:
    out = subprocess.run(["docker", "compose", "exec", "-T", service, "cat", path],
                         capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"cat {path} in {service} failed: {out.stderr.strip()[:200]}")
    return out.stdout


def api_login_from_inside(target: str, email: str, password: str) -> tuple[str, int, str]:
    """Log in from *inside* the api container, so the peer address is known exactly.

    Returns (the address that container sees as its own, status, Retry-After). The forged
    X-Forwarded-For goes along on every call: what this measures is whether the server reads it, and
    the answer must be "no" on both paths -- because the proxy overwrites the header, and because a
    peer that is not on the allow-list is not believed about anything.
    """
    code = ("import socket,sys,httpx;"
            "me=socket.gethostbyname(socket.gethostname());"
            "r=httpx.post(sys.argv[1],json={'email':sys.argv[2],'password':sys.argv[3]},"
            "headers={'X-Forwarded-For':'203.0.113.77'},timeout=30);"
            "print(me,r.status_code,r.headers.get('retry-after',''))")
    out = subprocess.run(["docker", "compose", "exec", "-T", "api", "python", "-c", code,
                          target, email, password], capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"login from inside api failed: {(out.stderr or out.stdout).strip()[:220]}")
    parts = out.stdout.strip().split()
    if len(parts) < 2:
        raise SystemExit(f"login from inside api returned an unreadable line: {out.stdout[:200]!r}")
    return parts[0], int(parts[1]), (parts[2] if len(parts) > 2 else "")


def newest_ip_hash(user_id: str) -> str:
    return sql(f"SELECT ip_hash FROM auth_sessions WHERE user_id='{user_id}' ORDER BY created_at DESC LIMIT 1")


def source_key(address: str, pepper: str) -> str:
    return f"login:src:{hashlib.sha256(f'{pepper}|{address}'.encode()).hexdigest()}"


def walk_source_accounts(count: int, email_prefix: str) -> list[int]:
    """One wrong password each for `count` accounts that do not exist, from inside the api container."""
    codes = []
    for i in range(count):
        _, status, _ = api_login_from_inside("http://127.0.0.1:8000/api/auth/login",
                                             f"{email_prefix}-{i}@example.local", PASSWORD)
        codes.append(status)
    return codes


def wait_out_challenge_window(user_id: str):
    """The challenge limiter is a 60s fixed window, so read it rather than sleeping blind.

    Sleeping a flat 61s would work too, but it would also hide a limiter whose TTL had been set
    wrong: this asks the store how much of the window is left, waits that much, and then requires
    the counter to be actually gone before the next measurement is taken.
    """
    key = f"mfa:challenge:{hashlib.sha256(user_id.encode()).hexdigest()}"
    for _ in range(10):
        ttl = int(redis_cli("TTL", key) or -2)
        if ttl < 0:
            return
        time.sleep(ttl + 1)


def status(token: str) -> dict:
    response = httpx.get(BASE + "/auth/mfa/status", headers=bearer(token), timeout=40)
    if response.status_code != 200:
        return {"_status": response.status_code, "_body": response.text[:200]}
    return response.json()


def stored_recovery_hashes(user_id: str) -> list[str]:
    raw = sql(f"SELECT mfa_recovery FROM users WHERE id='{user_id}'")
    return [entry["hash"] for entry in json.loads(raw)] if raw and raw != "-" else []


def main() -> int:
    probe_id = make_user(PROBE, "MFA Probe")
    window_id = make_user(WINDOW_PROBE, "MFA Window Probe")
    sessions_at = lambda: sql(f"SELECT count(*) FROM auth_sessions WHERE user_id='{probe_id}'")
    try:
        # ---- two password-only sessions exist before anything is armed ---------------
        first = sign_in(PROBE)
        check("an unarmed account still logs in with a password alone",
              first.status_code == 200 and "access_token" in first.json(), f"{first.status_code} {first.text[:200]}")
        s1 = first.json()["access_token"]
        second = sign_in(PROBE)
        s2 = second.json()["access_token"]
        check("a second session can be open at the same time", second.status_code == 200, f"{second.status_code}")
        check("that second session works before arming",
              httpx.get(BASE + "/auth/me", headers=bearer(s2), timeout=40).status_code == 200)
        check("and each login minted its own session row", sessions_at() == "2", sessions_at())

        # ---- enrolment is staged: a seed alone must not arm anything -----------------
        enrolled = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(s1), timeout=40)
        seed = enrolled.json().get("secret", "") if enrolled.status_code == 200 else ""
        uri = enrolled.json().get("provisioning_uri", "") if enrolled.status_code == 200 else ""
        check("enrolment returns a seed and an otpauth URI", bool(seed) and uri.startswith("otpauth://"),
              f"{enrolled.status_code} {enrolled.text[:200]}")
        check("the URI states the period and digits the server will verify with",
              "period=30" in uri and "digits=6" in uri, uri)
        # What a phone scans has to be what this response states, so the image is read back from the
        # bytes the API shipped -- with an independent decoder (zxing-cpp), not segno's own account of
        # what it drew. See scripts/requirements-drill.txt for the test-side dependency.
        qr_uri = enrolled.json().get("qr_png_data_uri", "")
        decoded = (e2e_client.decode_qr_data_uri(qr_uri)
                   if qr_uri.startswith("data:image/png;base64,") else "")
        check("the enrolment QR decodes to exactly the provisioning URI", decoded == uri,
              f"qr field {'present' if qr_uri else 'MISSING'}, decoded {str(decoded)[:90]!r}")
        check("and the symbol carries this account's own seed and address",
              bool(seed) and seed in str(decoded) and quote(PROBE, safe="") in str(decoded), str(decoded)[:140])
        state = status(s1)
        check("the seed is pending rather than armed", state.get("armed") is False and state.get("pending_since"), str(state))

        wrong = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": "000000"}, headers=bearer(s1), timeout=40)
        check("a wrong code does not arm the factor", wrong.status_code == 401, f"{wrong.status_code} {wrong.text[:160]}")
        check("and the account is still unarmed after it", status(s1).get("armed") is False)
        foreign = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(OTHER_SEED)},
                             headers=bearer(s1), timeout=40)
        check("a well-formed code for some other seed is refused too", foreign.status_code == 401,
              f"{foreign.status_code} {foreign.text[:160]}")

        # Starting over while a seed is still pending is allowed -- nothing is armed yet, so there
        # is no lockout to protect against -- but it has to actually replace the seed, or the
        # abandoned URI keeps working in parallel with the new one.
        replaced = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(s1), timeout=40)
        check("re-enrolment while pending is allowed and hands out a different seed",
              replaced.status_code == 200 and replaced.json().get("secret") not in ("", seed),
              f"{replaced.status_code} {replaced.text[:160]}")
        stale_seed = seed
        seed = replaced.json().get("secret", seed)
        check("and the abandoned seed stops being able to confirm",
              httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(stale_seed)},
                         headers=bearer(s1), timeout=40).status_code == 401)

        armed = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(seed)},
                           headers=bearer(s1), timeout=40)
        body = armed.json() if armed.status_code == 200 else {}
        recovery = body.get("recovery_codes") or []
        check("proof of knowledge arms it, and the recovery codes are shown once",
              armed.status_code == 200 and body.get("armed") is True and len(recovery) == 10,
              f"{armed.status_code} {armed.text[:200]}")
        stored = stored_recovery_hashes(probe_id)
        check("the database kept one hash per code and no plaintext",
              len(stored) == 10 and all(code not in str(stored) and len(code) == 10 for code in recovery),
              f"{len(stored)} hashes")
        old_hashes = set(stored)

        # ---- arming must not retro-authorise, and must not lock out ------------------
        after = status(s1)
        check("the session that proved the code keeps working and records the factor",
              after.get("armed") is True and after.get("session_amr") == "pwd,totp" and after.get("session_second_factor_at"),
              str(after))
        stale = httpx.get(BASE + "/auth/me", headers=bearer(s2), timeout=40)
        check("a session opened before arming is refused until it presents the factor",
              stale.status_code == 401 and "second factor" in stale.text, f"{stale.status_code} {stale.text[:160]}")

        # ---- the password alone now yields a pending credential, not a session -------
        response = sign_in(PROBE)
        challenged = response.json() if response.status_code == 200 else {}
        check("login now stops at a second factor",
              response.status_code == 200 and challenged.get("mfa_required") is True,
              f"{response.status_code} {response.text[:200]}")
        check("its body is nothing but the challenge",
              set(challenged) == {"mfa_required", "pending_token", "pending_expires_in"}, str(sorted(challenged)))
        check("no cookie is set for an unproven login",
              not [c for c in response.headers.get_list("set-cookie") if "resonance_access" in c],
              str(response.headers.get_list("set-cookie")))
        pending = challenged["pending_token"]
        smuggled = httpx.get(BASE + "/auth/me", headers=bearer(pending), timeout=40)
        check("a pending token is refused where an access token is expected",
              smuggled.status_code == 401 and "not an access token" in smuggled.text,
              f"{smuggled.status_code} {smuggled.text[:160]}")
        sessions_before = sessions_at()
        refused = challenge(pending, "000000")
        check("a wrong code at the challenge is refused", refused.status_code == 401, f"{refused.status_code} {refused.text[:160]}")
        check("and mints no session", sessions_at() == sessions_before, f"{sessions_before} -> {sessions_at()}")

        # The enrolment confirmation above consumed the current step, so start counting from it.
        codes = e2e_client.Codes(seed, used=int(time.time() // 30))
        good = codes.next()
        accepted = challenge(pending, good)
        granted = accepted.json() if accepted.status_code == 200 else {}
        check("the right code opens a session", accepted.status_code == 200 and "access_token" in granted,
              f"{accepted.status_code} {accepted.text[:200]}")
        s3 = granted.get("access_token", "")
        check("the challenge body has the same shape as a password-only login",
              set(granted) == set(first.json()), f"{sorted(granted)} vs {sorted(first.json())}")
        third = status(s3) if s3 else {}
        check("the new session records both factors",
              third.get("session_amr") == "pwd,totp" and third.get("session_second_factor_at"), str(third))

        replayed = challenge(pending, good)
        check("the same code cannot be spent twice on the same pending token",
              replayed.status_code == 401, f"{replayed.status_code} {replayed.text[:160]}")
        fresh = pending_token(PROBE)
        across = challenge(fresh, good)
        check("and not on a different pending token either, because the guard is per account",
              across.status_code == 401, f"{across.status_code} {across.text[:160]}")
        check("the replay guard is a stored step rather than process memory",
              sql(f"SELECT coalesce(mfa_last_step::text,'-') FROM users WHERE id='{probe_id}'") != "-")

        # ---- recovery codes: single use, and the count moves -------------------------
        remaining = third.get("recovery_codes_remaining")
        revived = challenge(fresh, recovery[0])
        check("a recovery code opens a session when the phone does not",
              revived.status_code == 200 and "access_token" in revived.json(), f"{revived.status_code} {revived.text[:160]}")
        s4 = revived.json().get("access_token", "")
        used = status(s4) if s4 else {}
        check("using one burns exactly one", used.get("recovery_codes_remaining") == (remaining or 0) - 1,
              f"{remaining} -> {used.get('recovery_codes_remaining')}")
        check("the recovery path is recorded as a distinct method", used.get("session_amr") == "pwd,recovery", str(used))
        check("and the spent code no longer opens anything", challenge(fresh, recovery[0]).status_code == 401)

        # ---- a pending enrolment nobody confirmed has to expire ----------------------
        window_first = sign_in(WINDOW_PROBE)
        window_token = window_first.json()["access_token"]
        began = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(window_token), timeout=40)
        check("a second probe can start its own enrolment", began.status_code == 200, f"{began.status_code} {began.text[:160]}")
        sql(f"UPDATE users SET mfa_secret_issued_at=now()-interval '2 hours' WHERE id='{window_id}'")
        expired = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(began.json()["secret"])},
                             headers=bearer(window_token), timeout=40)
        check("an enrolment left pending past the window cannot be confirmed",
              expired.status_code == 409 and "expired" in expired.text, f"{expired.status_code} {expired.text[:160]}")
        check("and that probe is still unarmed, so an abandoned enrolment locks nobody out",
              sql(f"SELECT (mfa_enrolled_at IS NULL)::text FROM users WHERE id='{window_id}'") == "true")

        # ---- revocation and rotation ------------------------------------------------
        bare = httpx.post(BASE + "/auth/mfa/disable", json={"code": "000000"}, headers=bearer(s1), timeout=40)
        check("dropping the factor asks for the password before anything else",
              bare.status_code == 401 and "password" in bare.text, f"{bare.status_code} {bare.text[:160]}")
        check("and the account stays armed when it is refused", status(s1).get("armed") is True)
        # The code is the half an attacker can still hand over after phishing it; the password is the
        # half a stolen cookie does not carry. Order is the point, and so is what must not happen: a
        # refusal at the password wall must leave the code unspent and still usable.
        proof = codes.next()
        badpw = httpx.post(BASE + "/auth/mfa/disable", json={"code": proof, "password": "not-the-password"},
                           headers=bearer(s1), timeout=40)
        check("a wrong password refuses the drop even while the code is currently valid",
              badpw.status_code == 403 and "password" in badpw.text, f"{badpw.status_code} {badpw.text[:160]}")
        check("the refusal left the second factor armed", status(s1).get("armed") is True)
        again = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(s1), timeout=40)
        check("an armed second factor cannot be replaced behind its own back",
              again.status_code == 409, f"{again.status_code} {again.text[:160]}")

        disabled = httpx.post(BASE + "/auth/mfa/disable", json={"code": proof, "password": PASSWORD},
                              headers=bearer(s1), timeout=40)
        check("the very same code drops the factor once the password is right",
              disabled.status_code == 200 and disabled.json().get("armed") is False, f"{disabled.status_code} {disabled.text[:160]}")
        row = sql(f"SELECT coalesce(mfa_secret_enc,'-')||'|'||coalesce(mfa_recovery::text,'-')||'|'||(mfa_enrolled_at IS NULL)::text"
                  f"||'|'||coalesce(mfa_last_step::text,'-') FROM users WHERE id='{probe_id}'")
        check("seed, recovery set, armed marker and replay step are all gone", row == "-|-|true|-", row)
        plain = sign_in(PROBE)
        check("password-only login works again", plain.status_code == 200 and "access_token" in plain.json()
              and not plain.json().get("mfa_required"), f"{plain.status_code} {plain.text[:160]}")
        check("the disarmed sessions are not retroactively refused",
              httpx.get(BASE + "/auth/me", headers=bearer(s2), timeout=40).status_code == 200)

        # ---- re-enrolment: a fresh seed, and the old recovery set stops working ------
        arm = httpx.post(BASE + "/auth/mfa/enroll", headers=bearer(plain.json()["access_token"]), timeout=40)
        new_seed = arm.json().get("secret", "")
        confirmed = httpx.post(BASE + "/auth/mfa/enroll/verify", json={"code": e2e_client.totp_code(new_seed)},
                               headers=bearer(plain.json()["access_token"]), timeout=40)
        new_recovery = confirmed.json().get("recovery_codes") or []
        check("re-enrolment arms a fresh seed with a fresh recovery set",
              confirmed.status_code == 200 and confirmed.json().get("armed") is True and len(new_recovery) == 10,
              f"{confirmed.status_code} {confirmed.text[:160]}")
        wait_out_challenge_window(probe_id)
        stale_code = challenge(pending_token(PROBE), recovery[1])
        check("the previous recovery set stops working the moment it is replaced",
              stale_code.status_code == 401, f"{stale_code.status_code} {stale_code.text[:160]}")
        rotated = set(stored_recovery_hashes(probe_id))
        check("and its hashes are gone from the stored set, not merely unused",
              bool(rotated) and not (rotated & old_hashes) and len(rotated) == 10,
              f"{len(rotated)} kept, {len(rotated & old_hashes)} inherited")

        # ---- the code oracle gets a bounded window, and it outranks a valid code -----
        # Everything above shares this account's counter, so the measurements below only mean
        # anything from a quiet window; wait_out_challenge_window(probe_id) cleared one.
        new_codes = e2e_client.Codes(new_seed, used=int(time.time() // 30))
        throttled = pending_token(PROBE)
        statuses = [challenge(throttled, "111111").status_code for _ in range(12)]
        limit = statuses.index(429) + 1 if 429 in statuses else None
        check("repeated wrong codes are throttled", limit is not None, f"statuses: {statuses}")
        check("the throttle does not fire on the first attempt", bool(limit) and limit > 1, f"429 at attempt {limit}")
        check("and the window is monotone: nothing succeeds after it has filled",
              limit is not None and set(statuses[:limit - 1]) == {401} and set(statuses[limit - 1:]) == {429},
              f"statuses: {statuses}")
        key = f"mfa:challenge:{hashlib.sha256(probe_id.encode()).hexdigest()}"
        ttl = int(redis_cli("TTL", key) or -2)
        check("the counter is a bounded window in the shared store, not a permanent lock",
              0 < ttl <= 60, f"key {key} TTL {ttl}")
        if limit:
            outranked = challenge(throttled, new_codes.next())
            check("while throttled, even a correct code is refused", outranked.status_code == 429,
                  f"{outranked.status_code} {outranked.text[:120]}")
            time.sleep(max(ttl, 1) + 2)
            released = httpx.post(BASE + "/auth/mfa/disable", json={"code": new_codes.next(), "password": PASSWORD},
                                  headers=bearer(plain.json()["access_token"]), timeout=40)
            check("when the window passes the account is usable again, not locked out",
                  released.status_code == 200, f"{released.status_code} {released.text[:160]}")

        # ---- the login door: a fixed window that only a failed credential can extend ----
        # Read against the counter in the shared store, not inferred from status codes. Before this round
        # the login key refreshed its TTL on every INCR -- refused attempts included -- so the window was
        # really "sixty seconds since the last knock" (75s of silence was needed to observe recovery), and
        # a *successful* login spent a unit of it, which is why the browser gate had to wait a minute just
        # to authenticate the same owner eight times. Both properties are tested for here, and each one is
        # the kind that comes back on its own if nobody is looking at the store.
        per_minute = int(api_env("LOGIN_RATE_LIMIT_PER_MINUTE"))
        login_key = f"login:{hashlib.sha256(WINDOW_PROBE.lower().encode()).hexdigest()}"
        redis_cli("DEL", login_key)
        quiet = [sign_in(WINDOW_PROBE).status_code for _ in range(per_minute + 2)]
        check(f"{per_minute + 2} successful logins in a row cannot fill the window",
              set(quiet) == {200}, f"statuses: {quiet}")
        check("and they leave the counter empty, because only a failed credential is counted",
              redis_cli("EXISTS", login_key) == "0",
              f"key {login_key} reads {redis_cli('GET', login_key) or '-'} after {per_minute + 2} logins")
        statuses = [httpx.post(BASE + "/auth/login", json={"email": WINDOW_PROBE, "password": f"wrong-{n}"},
                               timeout=40).status_code for n in range(per_minute + 5)]
        limit = statuses.index(429) + 1 if 429 in statuses else None
        check("repeated wrong passwords are throttled", limit is not None, f"statuses: {statuses}")
        check(f"the window opens after exactly {per_minute} failed credentials, not before",
              limit == per_minute + 1, f"first refusal at attempt {limit}, statuses: {statuses}")
        check("and it is monotone: nothing succeeds once it is full",
              limit is not None and set(statuses[:limit - 1]) == {401} and set(statuses[limit - 1:]) == {429},
              f"statuses: {statuses}")
        # The wall sits in front of the credential check, so knowing the password buys nothing while the
        # window is full -- and because a refusal spends nothing, this attempt must not move the counter.
        outranked = sign_in(WINDOW_PROBE)
        check("while throttled, even the right password is refused", outranked.status_code == 429,
              f"{outranked.status_code} {outranked.text[:160]}")
        filled = redis_cli("GET", login_key)
        ttl = int(redis_cli("TTL", login_key) or -2)
        check("the counter is a bounded window in the shared store, not a permanent lock",
              0 < ttl <= 60, f"key {login_key} TTL {ttl}")
        retry_after = outranked.headers.get("Retry-After", "")
        check("the refusal says how long to wait, and says the window's own number",
              retry_after.isdigit() and 0 < int(retry_after) <= 60 and abs(int(retry_after) - ttl) <= 2,
              f"Retry-After {retry_after!r} against TTL {ttl}")
        # Decay has to be measured *while* the door is being knocked on: a nap after the last refusal lets
        # even a refreshing limiter count down, and that is how the first version of this check read green
        # against the pre-fix script. So the traffic runs until two seconds of wall time have gone by, the
        # number of refused requests it fit in is reported, and the window is required to have spent about
        # that much of itself -- which a limiter that re-arms on every refusal cannot do.
        ttl_before = ttl
        knocked, started = 0, time.monotonic()
        while time.monotonic() - started < 2.0:
            httpx.post(BASE + "/auth/login", json={"email": WINDOW_PROBE, "password": "again"}, timeout=40)
            knocked += 1
        elapsed = time.monotonic() - started
        after = redis_cli("GET", login_key)
        ttl_after = int(redis_cli("TTL", login_key) or -2)
        check("a refusal spends none of the window it reports",
              filled == after == str(per_minute),
              f"counter read {filled!r} then {after!r} against a limit of {per_minute}")
        check(f"the window kept counting down through {knocked} refused requests in {elapsed:.1f}s "
              "instead of restarting",
              knocked >= 5 and 0 < ttl_after <= ttl_before - 1,
              f"TTL {ttl_before} then {ttl_after} after {elapsed:.1f}s of refusals")
        time.sleep(max(ttl_after, 1) + 2)
        reopened = sign_in(WINDOW_PROBE)
        check("when the window passes the account signs in, so this is throttling and not a lockout",
              reopened.status_code == 200, f"{reopened.status_code} {reopened.text[:160]}")
        redis_cli("DEL", login_key)

        # ---- the address dimension: who the server is allowed to believe ----------------
        # Everything above holds one account down; this holds one *machine* down, and it only exists
        # because the api now has a client address it may trust. Both halves are measured, because the
        # dangerous failure of a trust list is not an error -- it is the old silent behaviour coming
        # back while every request still succeeds.
        pepper = api_env("ADDRESS_PEPPER")
        trusted = api_env("FORWARDED_ALLOW_IPS")
        gateway_ip = container_ip("gateway")
        check("the api names exactly one peer whose forwarding it believes, and that peer is the gateway",
              bool(pepper) and bool(trusted) and trusted == gateway_ip and "*" not in trusted,
              f"FORWARDED_ALLOW_IPS={trusted!r}, gateway container={gateway_ip!r}")
        shipped = container_file("gateway", "/etc/nginx/conf.d/default.conf")
        # Directive lines only. The comment that explains *why* appending is wrong names the variable it
        # forbids, so a substring test over the whole file can never go green -- and would also pass on a
        # config whose appends were merely commented out.
        active = [x.strip() for x in shipped.splitlines() if x.strip() and not x.strip().startswith("#")]
        # Counted over the directives that set this header, not over proxy_pass: four of the api's
        # locations (/docs, /openapi.json, /health, /ready) carry no credentials and no rate limit, so
        # they need no client chain, and demanding a directive on each of them would only teach the
        # next reader to add one.
        forwarders = [x for x in active if x.startswith("proxy_set_header X-Forwarded-For")]
        writes = sum(1 for x in forwarders if "$remote_addr" in x)
        appends = sum(1 for x in forwarders if "proxy_add_x_forwarded_for" in x)
        check(f"all {len(forwarders)} directives that set the client chain write it rather than appending",
              len(forwarders) >= 2 and appends == 0 and writes == len(forwarders),
              f"{writes} writing, {appends} appending, over {len(forwarders)} X-Forwarded-For directives "
              f"among {len(active)} active lines")
        check("the recorded address is a keyed digest, not a bare hash of an address",
              "ip_hash" in sql("SELECT string_agg(column_name,',') FROM information_schema.columns "
                               "WHERE table_name='auth_sessions'")
              and pepper != "",
              "auth_sessions.ip_hash missing, or no pepper configured")

        before = sql(f"SELECT count(*) FROM auth_sessions WHERE user_id='{probe_id}'")
        mine, via_status, _ = api_login_from_inside("http://gateway/api/auth/login", PROBE, PASSWORD)
        over_gateway = newest_ip_hash(probe_id)
        keyed = lambda value: hashlib.sha256(f"{pepper}|{value}".encode()).hexdigest()
        check(f"a login through the gateway records the address the gateway itself saw ({mine}), "
              "not the forged header and not the proxy",
              via_status == 200 and over_gateway == keyed(mine)
              and over_gateway != keyed("203.0.113.77") and over_gateway != keyed(gateway_ip),
              f"status {via_status}, stored {over_gateway[:16]}…, expected {keyed(mine)[:16]}… "
              f"(forged would be {keyed('203.0.113.77')[:16]}…, gateway {keyed(gateway_ip)[:16]}…)")
        _, direct_status, _ = api_login_from_inside("http://127.0.0.1:8000/api/auth/login", PROBE, PASSWORD)
        direct_hash = newest_ip_hash(probe_id)
        check("the same forged header arriving on the published port is ignored too, because that peer "
              "is not on the list",
              direct_status == 200 and direct_hash == keyed("127.0.0.1")
              and direct_hash != keyed("203.0.113.77"),
              f"status {direct_status}, stored {direct_hash[:16]}…, expected {keyed('127.0.0.1')[:16]}…")
        check("and no stored row is the unsalted digest of any of those addresses",
              sql(f"SELECT count(*) FROM auth_sessions WHERE user_id='{probe_id}' AND ip_hash IN ("
                  f"'{hashlib.sha256(mine.encode()).hexdigest()}',"
                  f"'{hashlib.sha256('127.0.0.1'.encode()).hexdigest()}',"
                  f"'{hashlib.sha256('203.0.113.77'.encode()).hexdigest()}',"
                  f"'{hashlib.sha256(gateway_ip.encode()).hexdigest()}')") == "0",
              "an unsalted address digest is still being written")
        check("the two probe logins minted exactly two more sessions and nothing else",
              sql(f"SELECT count(*) FROM auth_sessions WHERE user_id='{probe_id}'")
              == str(int(before) + 2), f"rows went {before} -> {sessions_at()}")

        per_source = int(api_env("LOGIN_SOURCE_RATE_LIMIT_PER_MINUTE"))
        src_key = source_key("127.0.0.1", pepper)
        redis_cli("DEL", src_key)
        walk_prefix = f"mfa-walk-{STAMP}"
        codes = walk_source_accounts(per_source, walk_prefix)
        check(f"a source may get {per_source} different accounts wrong in a window, which is the point",
              codes == [401] * per_source, f"statuses: {codes}")
        held, held_status, held_retry = api_login_from_inside("http://127.0.0.1:8000/api/auth/login",
                                                              f"{walk_prefix}-x@example.local", PASSWORD)
        check(f"one account past the {per_source} the window allows is refused from the same source, "
              f"with the wait stated",
              held_status == 429 and held_retry.isdigit() and 0 < int(held_retry) <= 60,
              f"status {held_status}, Retry-After {held_retry!r}")
        card_full = int(redis_cli("SCARD", src_key) or -1)
        ttl_full = int(redis_cli("TTL", src_key) or -2)
        again = walk_source_accounts(3, f"{walk_prefix}-more")
        check("a refusal adds nothing to the window it reports, and the window keeps running down",
              again == [429, 429, 429] and int(redis_cli("SCARD", src_key) or -1) == card_full
              and 0 < int(redis_cli("TTL", src_key) or -2) <= ttl_full,
              f"statuses {again}, cardinality {card_full} then {redis_cli('SCARD', src_key)}, "
              f"ttl {ttl_full} then {redis_cli('TTL', src_key)}")
        redis_cli("DEL", src_key)
        released, released_status, _ = api_login_from_inside("http://127.0.0.1:8000/api/auth/login",
                                                             f"{walk_prefix}-x@example.local", PASSWORD)
        check("clearing the window is enough: nothing was written about the account itself",
              released_status == 401,
              f"the held address now answers {released_status} ({released!r}) -- a held source must be "
              "throttling, not a ban that outlives the window")
        one_key = source_key("127.0.0.1", pepper)
        redis_cli("DEL", one_key)
        same_email = f"mfa-same-{STAMP}@example.local"
        singles = [api_login_from_inside("http://127.0.0.1:8000/api/auth/login", same_email, PASSWORD)[1]
                   for _ in range(5)]
        check("five mistypes by one account are one account: the source window does not notice them",
              singles == [401] * 5 and int(redis_cli("SCARD", one_key) or -1) == 1,
              f"statuses {singles}, cardinality {redis_cli('SCARD', one_key)}")
        redis_cli("DEL", one_key)

        # Precise, because the window probe deliberately leaves something behind: an abandoned
        # enrolment keeps its sealed seed until the account re-enrols, is disarmed or is erased.
        # It is inert -- 015's confirm refuses it past the window, which is the check above -- but a
        # count on "holds any second-factor material" would report it and hide the real question,
        # which is whether anything can still be *unlocked* by what is stored.
        check("no account left behind can be unlocked by a second factor",
              sql("SELECT count(*) FROM users WHERE mfa_enrolled_at IS NOT NULL OR "
                  "(mfa_secret_enc IS NOT NULL AND mfa_secret_issued_at > now()-interval '900 seconds')") == "0",
              sql("SELECT string_agg(email||'='||coalesce(mfa_enrolled_at::text,'-'),', ') FROM users "
                  "WHERE mfa_secret_enc IS NOT NULL OR mfa_enrolled_at IS NOT NULL"))
    finally:
        for email, user_id in ((PROBE, probe_id), (WINDOW_PROBE, window_id)):
            sql(f"DELETE FROM auth_sessions WHERE user_id='{user_id}'")
            sql(f"DELETE FROM user_preferences WHERE user_id='{user_id}'")
            sql(f"DELETE FROM workspace_members WHERE user_id='{user_id}'")
            sql(f"DELETE FROM users WHERE id='{user_id}'")
        left = sql(f"SELECT count(*) FROM users WHERE id IN ('{probe_id}','{window_id}')")
        sealed = sql("SELECT count(*) FROM users WHERE mfa_secret_enc IS NOT NULL OR mfa_enrolled_at IS NOT NULL")
        events = sql(f"SELECT count(*) FROM audit_events WHERE action LIKE 'auth.mfa.%'")
        print(f"  teardown: probe accounts deleted ({left} still present); accounts on this stack still "
              f"holding second-factor material: {sealed}; auth.mfa.* audit rows retained by design: {events}")

    failed = [name for name, passed, _ in checks if not passed]
    print(f"\nmfa drill: {len(checks) - len(failed)}/{len(checks)} checks passed")
    for name in failed:
        print(f"  - {name}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
